[package]
name = "layouter"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = {version = "0.28.1", features = ["event-stream", "events"]}
ratatui = "0.28.0"
hidapi = "2.6.3"
tokio = {version = "1.39.2", features = ["full"]}
futures = "0.3.30"
